# Терминологический словарь для новостного переводчика
# Мультиязычный словарь: ключ - английский термин, значение - dict с переводами
# Регистронезависимый (используется re.IGNORECASE)

TERMINOLOGY_DICT = {
    # Компании и бренды (бренды часто остаются на английском)
    "Apple": {"en": "Apple", "ru": "Apple", "de": "Apple", "fr": "Apple"},
    "Google": {"en": "Google", "ru": "Google", "de": "Google", "fr": "Google"},
    "Microsoft": {"en": "Microsoft", "ru": "Microsoft", "de": "Microsoft", "fr": "Microsoft"},
    "Samsung": {"en": "Samsung", "ru": "Samsung", "de": "Samsung", "fr": "Samsung"},
    "Sony": {"en": "Sony", "ru": "Sony", "de": "Sony", "fr": "Sony"},
    "Tesla": {"en": "Tesla", "ru": "Tesla", "de": "Tesla", "fr": "Tesla"},
    "Netflix": {"en": "Netflix", "ru": "Netflix", "de": "Netflix", "fr": "Netflix"},
    "Meta": {"en": "Meta", "ru": "Meta", "de": "Meta", "fr": "Meta"},
    "Amazon": {"en": "Amazon", "ru": "Amazon", "de": "Amazon", "fr": "Amazon"},
    "Intel": {"en": "Intel", "ru": "Intel", "de": "Intel", "fr": "Intel"},
    "NVIDIA": {"en": "NVIDIA", "ru": "NVIDIA", "de": "NVIDIA", "fr": "NVIDIA"},
    "AMD": {"en": "AMD", "ru": "AMD", "de": "AMD", "fr": "AMD"},
    "Adobe": {"en": "Adobe", "ru": "Adobe", "de": "Adobe", "fr": "Adobe"},
    "Oracle": {"en": "Oracle", "ru": "Oracle", "de": "Oracle", "fr": "Oracle"},
    "IBM": {"en": "IBM", "ru": "IBM", "de": "IBM", "fr": "IBM"},
    "Cisco": {"en": "Cisco", "ru": "Cisco", "de": "Cisco", "fr": "Cisco"},
    "Salesforce": {"en": "Salesforce", "ru": "Salesforce", "de": "Salesforce", "fr": "Salesforce"},
    "SAP": {"en": "SAP", "ru": "SAP", "de": "SAP", "fr": "SAP"},
    "Dell": {"en": "Dell", "ru": "Dell", "de": "Dell", "fr": "Dell"},
    "HP": {"en": "HP", "ru": "HP", "de": "HP", "fr": "HP"},
    "Lenovo": {"en": "Lenovo", "ru": "Lenovo", "de": "Lenovo", "fr": "Lenovo"},
    "Huawei": {"en": "Huawei", "ru": "Huawei", "de": "Huawei", "fr": "Huawei"},
    "Xiaomi": {"en": "Xiaomi", "ru": "Xiaomi", "de": "Xiaomi", "fr": "Xiaomi"},
    "TikTok": {"en": "TikTok", "ru": "TikTok", "de": "TikTok", "fr": "TikTok"},
    "ByteDance": {"en": "ByteDance", "ru": "ByteDance", "de": "ByteDance", "fr": "ByteDance"},
    "Uber": {"en": "Uber", "ru": "Uber", "de": "Uber", "fr": "Uber"},
    "Airbnb": {"en": "Airbnb", "ru": "Airbnb", "de": "Airbnb", "fr": "Airbnb"},
    "Spotify": {"en": "Spotify", "ru": "Spotify", "de": "Spotify", "fr": "Spotify"},
    "Twitter": {"en": "Twitter", "ru": "Twitter", "de": "Twitter", "fr": "Twitter"},
    "Facebook": {"en": "Facebook", "ru": "Facebook", "de": "Facebook", "fr": "Facebook"},
    "Instagram": {"en": "Instagram", "ru": "Instagram", "de": "Instagram", "fr": "Instagram"},
    "LinkedIn": {"en": "LinkedIn", "ru": "LinkedIn", "de": "LinkedIn", "fr": "LinkedIn"},
    "WhatsApp": {"en": "WhatsApp", "ru": "WhatsApp", "de": "WhatsApp", "fr": "WhatsApp"},
    "Telegram": {"en": "Telegram", "ru": "Telegram", "de": "Telegram", "fr": "Telegram"},
    "Discord": {"en": "Discord", "ru": "Discord", "de": "Discord", "fr": "Discord"},
    "Slack": {"en": "Slack", "ru": "Slack", "de": "Slack", "fr": "Slack"},
    "Zoom": {"en": "Zoom", "ru": "Zoom", "de": "Zoom", "fr": "Zoom"},
    "Twitch": {"en": "Twitch", "ru": "Twitch", "de": "Twitch", "fr": "Twitch"},
    "Disney+": {"en": "Disney+", "ru": "Disney+", "de": "Disney+", "fr": "Disney+"},
    "HBO Max": {"en": "HBO Max", "ru": "HBO Max", "de": "HBO Max", "fr": "HBO Max"},
    "Apple TV+": {"en": "Apple TV+", "ru": "Apple TV+", "de": "Apple TV+", "fr": "Apple TV+"},
    "Amazon Prime Video": {"en": "Amazon Prime Video", "ru": "Amazon Prime Video", "de": "Amazon Prime Video", "fr": "Amazon Prime Video"},
    "YouTube": {"en": "YouTube", "ru": "YouTube", "de": "YouTube", "fr": "YouTube"},
    "Snapchat": {"en": "Snapchat", "ru": "Snapchat", "de": "Snapchat", "fr": "Snapchat"},
    "Pinterest": {"en": "Pinterest", "ru": "Pinterest", "de": "Pinterest", "fr": "Pinterest"},
    "Reddit": {"en": "Reddit", "ru": "Reddit", "de": "Reddit", "fr": "Reddit"},
    "Quora": {"en": "Quora", "ru": "Quora", "de": "Quora", "fr": "Quora"},
    "Medium": {"en": "Medium", "ru": "Medium", "de": "Medium", "fr": "Medium"},
    "Wikipedia": {"en": "Wikipedia", "ru": "Wikipedia", "de": "Wikipedia", "fr": "Wikipedia"},
    "GitHub": {"en": "GitHub", "ru": "GitHub", "de": "GitHub", "fr": "GitHub"},
    "GitLab": {"en": "GitLab", "ru": "GitLab", "de": "GitLab", "fr": "GitLab"},
    "Stack Overflow": {"en": "Stack Overflow", "ru": "Stack Overflow", "de": "Stack Overflow", "fr": "Stack Overflow"},
    "Mozilla": {"en": "Mozilla", "ru": "Mozilla", "de": "Mozilla", "fr": "Mozilla"},
    "Firefox": {"en": "Firefox", "ru": "Firefox", "de": "Firefox", "fr": "Firefox"},
    "Chrome": {"en": "Chrome", "ru": "Chrome", "de": "Chrome", "fr": "Chrome"},
    "Safari": {"en": "Safari", "ru": "Safari", "de": "Safari", "fr": "Safari"},
    "Edge": {"en": "Edge", "ru": "Edge", "de": "Edge", "fr": "Edge"},
    "Opera": {"en": "Opera", "ru": "Opera", "de": "Opera", "fr": "Opera"},
    "Brave": {"en": "Brave", "ru": "Brave", "de": "Brave", "fr": "Brave"},
    "Tor Browser": {"en": "Tor Browser", "ru": "Tor Browser", "de": "Tor Browser", "fr": "Tor Browser"},

    # Криптовалюты
    "Bitcoin": {"en": "Bitcoin", "ru": "Bitcoin", "de": "Bitcoin", "fr": "Bitcoin"},
    "Ethereum": {"en": "Ethereum", "ru": "Ethereum", "de": "Ethereum", "fr": "Ethereum"},
    "Dogecoin": {"en": "Dogecoin", "ru": "Dogecoin", "de": "Dogecoin", "fr": "Dogecoin"},
    "Ripple": {"en": "Ripple", "ru": "Ripple", "de": "Ripple", "fr": "Ripple"},
    "Litecoin": {"en": "Litecoin", "ru": "Litecoin", "de": "Litecoin", "fr": "Litecoin"},
    "Solana": {"en": "Solana", "ru": "Solana", "de": "Solana", "fr": "Solana"},
    "Cardano": {"en": "Cardano", "ru": "Cardano", "de": "Cardano", "fr": "Cardano"},
    "Polkadot": {"en": "Polkadot", "ru": "Polkadot", "de": "Polkadot", "fr": "Polkadot"},
    "Chainlink": {"en": "Chainlink", "ru": "Chainlink", "de": "Chainlink", "fr": "Chainlink"},
    "Uniswap": {"en": "Uniswap", "ru": "Uniswap", "de": "Uniswap", "fr": "Uniswap"},

    # ИИ и технологии (с переводами)
    "OpenAI": {"en": "OpenAI", "ru": "OpenAI", "de": "OpenAI", "fr": "OpenAI"},
    "ChatGPT": {"en": "ChatGPT", "ru": "ChatGPT", "de": "ChatGPT", "fr": "ChatGPT"},
    "GPT-3": {"en": "GPT-3", "ru": "GPT-3", "de": "GPT-3", "fr": "GPT-3"},
    "GPT-4": {"en": "GPT-4", "ru": "GPT-4", "de": "GPT-4", "fr": "GPT-4"},
    "Bard": {"en": "Bard", "ru": "Bard", "de": "Bard", "fr": "Bard"},
    "Claude": {"en": "Claude", "ru": "Claude", "de": "Claude", "fr": "Claude"},
    "Perplexity": {"en": "Perplexity", "ru": "Perplexity", "de": "Perplexity", "fr": "Perplexity"},
    "Midjourney": {"en": "Midjourney", "ru": "Midjourney", "de": "Midjourney", "fr": "Midjourney"},
    "DALL-E": {"en": "DALL-E", "ru": "DALL-E", "de": "DALL-E", "fr": "DALL-E"},
    "Stable Diffusion": {"en": "Stable Diffusion", "ru": "Stable Diffusion", "de": "Stable Diffusion", "fr": "Stable Diffusion"},
    "Artificial Intelligence": {"en": "Artificial Intelligence", "ru": "Искусственный интеллект", "de": "Künstliche Intelligenz", "fr": "Intelligence Artificielle"},
    "Machine Learning": {"en": "Machine Learning", "ru": "Машинное обучение", "de": "Maschinelles Lernen", "fr": "Apprentissage Automatique"},
    "Deep Learning": {"en": "Deep Learning", "ru": "Глубокое обучение", "de": "Deep Learning", "fr": "Apprentissage Profond"},
    "Neural Network": {"en": "Neural Network", "ru": "Нейронная сеть", "de": "Neuronales Netzwerk", "fr": "Réseau de Neurones"},
    "Blockchain": {"en": "Blockchain", "ru": "Блокчейн", "de": "Blockchain", "fr": "Blockchain"},
    "Cryptocurrency": {"en": "Cryptocurrency", "ru": "Криптовалюта", "de": "Kryptowährung", "fr": "Cryptomonnaie"},
    "Big Data": {"en": "Big Data", "ru": "Большие данные", "de": "Big Data", "fr": "Big Data"},
    "Cloud Computing": {"en": "Cloud Computing", "ru": "Облачные вычисления", "de": "Cloud Computing", "fr": "Informatique en Nuage"},
    "Internet of Things": {"en": "Internet of Things", "ru": "Интернет вещей", "de": "Internet der Dinge", "fr": "Internet des Objets"},
    "Augmented Reality": {"en": "Augmented Reality", "ru": "Дополненная реальность", "de": "Erweiterte Realität", "fr": "Réalité Augmentée"},
    "Virtual Reality": {"en": "Virtual Reality", "ru": "Виртуальная реальность", "de": "Virtuelle Realität", "fr": "Réalité Virtuelle"},
    "Quantum Computing": {"en": "Quantum Computing", "ru": "Квантовые вычисления", "de": "Quantencomputing", "fr": "Informatique Quantique"}
}